# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "onwijs"
license = "MIT"
licenselink = "https://github.com/jochemkossen/onwijs/blob/master/LICENSE"
description = ""
homepage = "https://onwijs.maankat.nl/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Jochem Kossen"
  homepage = "https://jkossen.nl"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
